package com.actop.db;
// Generated Jul 24, 2015 12:22:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AllowanceApproval generated by hbm2java
 */
@Entity
@Table(name="allowance_approval"
    ,catalog="actop_system"
)
public class AllowanceApproval  implements java.io.Serializable {


     private Integer employersHasAllowancesHasDepartmentsHasDesignationId;
     private DepartmentsHasDesignation departmentsHasDesignation;
     private EmployersHasAllowances employersHasAllowances;
     private Date approvedtime;
     private Integer status;
     private String note;

    public AllowanceApproval() {
    }

	
    public AllowanceApproval(DepartmentsHasDesignation departmentsHasDesignation, EmployersHasAllowances employersHasAllowances) {
        this.departmentsHasDesignation = departmentsHasDesignation;
        this.employersHasAllowances = employersHasAllowances;
    }
    public AllowanceApproval(DepartmentsHasDesignation departmentsHasDesignation, EmployersHasAllowances employersHasAllowances, Date approvedtime, Integer status, String note) {
       this.departmentsHasDesignation = departmentsHasDesignation;
       this.employersHasAllowances = employersHasAllowances;
       this.approvedtime = approvedtime;
       this.status = status;
       this.note = note;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="EMPLOYERS_has_ALLOWANCES_has_DEPARTMENTS_has_DESIGNATION_ID", unique=true, nullable=false)
    public Integer getEmployersHasAllowancesHasDepartmentsHasDesignationId() {
        return this.employersHasAllowancesHasDepartmentsHasDesignationId;
    }
    
    public void setEmployersHasAllowancesHasDepartmentsHasDesignationId(Integer employersHasAllowancesHasDepartmentsHasDesignationId) {
        this.employersHasAllowancesHasDepartmentsHasDesignationId = employersHasAllowancesHasDepartmentsHasDesignationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEPARTMENTS_has_DESIGNATION_ID_DEPARTMENTS_has_DESIGNATION", nullable=false)
    public DepartmentsHasDesignation getDepartmentsHasDesignation() {
        return this.departmentsHasDesignation;
    }
    
    public void setDepartmentsHasDesignation(DepartmentsHasDesignation departmentsHasDesignation) {
        this.departmentsHasDesignation = departmentsHasDesignation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYERS_has_ALLOWANCES_ID_EMPLOYERS_has_ALLOWANCES", nullable=false)
    public EmployersHasAllowances getEmployersHasAllowances() {
        return this.employersHasAllowances;
    }
    
    public void setEmployersHasAllowances(EmployersHasAllowances employersHasAllowances) {
        this.employersHasAllowances = employersHasAllowances;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPROVEDTIME", length=19)
    public Date getApprovedtime() {
        return this.approvedtime;
    }
    
    public void setApprovedtime(Date approvedtime) {
        this.approvedtime = approvedtime;
    }

    
    @Column(name="STATUS")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="NOTE")
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


