package com.actop.db;
// Generated Jul 11, 2015 12:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Allowances generated by hbm2java
 */
@Entity
@Table(name="allowances"
    ,catalog="actop_system"
)
public class Allowances  implements java.io.Serializable {


     private Integer idAllowances;
     private byte[] allowanceType;
     private Double allownceMinimum;
     private Double allowanceMaximum;
     private Integer status;
     private Set<EmployersHasAllowances> employersHasAllowanceses = new HashSet<EmployersHasAllowances>(0);

    public Allowances() {
    }

    public Allowances(byte[] allowanceType, Double allownceMinimum, Double allowanceMaximum, Integer status, Set<EmployersHasAllowances> employersHasAllowanceses) {
       this.allowanceType = allowanceType;
       this.allownceMinimum = allownceMinimum;
       this.allowanceMaximum = allowanceMaximum;
       this.status = status;
       this.employersHasAllowanceses = employersHasAllowanceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_ALLOWANCES", unique=true, nullable=false)
    public Integer getIdAllowances() {
        return this.idAllowances;
    }
    
    public void setIdAllowances(Integer idAllowances) {
        this.idAllowances = idAllowances;
    }

    
    @Column(name="ALLOWANCE_TYPE")
    public byte[] getAllowanceType() {
        return this.allowanceType;
    }
    
    public void setAllowanceType(byte[] allowanceType) {
        this.allowanceType = allowanceType;
    }

    
    @Column(name="ALLOWNCE_MINIMUM", precision=22, scale=0)
    public Double getAllownceMinimum() {
        return this.allownceMinimum;
    }
    
    public void setAllownceMinimum(Double allownceMinimum) {
        this.allownceMinimum = allownceMinimum;
    }

    
    @Column(name="ALLOWANCE_MAXIMUM", precision=22, scale=0)
    public Double getAllowanceMaximum() {
        return this.allowanceMaximum;
    }
    
    public void setAllowanceMaximum(Double allowanceMaximum) {
        this.allowanceMaximum = allowanceMaximum;
    }

    
    @Column(name="STATUS")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="allowances")
    public Set<EmployersHasAllowances> getEmployersHasAllowanceses() {
        return this.employersHasAllowanceses;
    }
    
    public void setEmployersHasAllowanceses(Set<EmployersHasAllowances> employersHasAllowanceses) {
        this.employersHasAllowanceses = employersHasAllowanceses;
    }




}


