package com.actop.db;
// Generated Jul 24, 2015 12:22:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attendance generated by hbm2java
 */
@Entity
@Table(name="attendance"
    ,catalog="actop_system"
)
public class Attendance  implements java.io.Serializable {


     private Integer idAttendance;
     private Employers employers;
     private Date attendanceDate;
     private Date dateTime;

    public Attendance() {
    }

	
    public Attendance(Employers employers) {
        this.employers = employers;
    }
    public Attendance(Employers employers, Date attendanceDate, Date dateTime) {
       this.employers = employers;
       this.attendanceDate = attendanceDate;
       this.dateTime = dateTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_ATTENDANCE", unique=true, nullable=false)
    public Integer getIdAttendance() {
        return this.idAttendance;
    }
    
    public void setIdAttendance(Integer idAttendance) {
        this.idAttendance = idAttendance;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYERS_ID_EMPLOYERS", nullable=false)
    public Employers getEmployers() {
        return this.employers;
    }
    
    public void setEmployers(Employers employers) {
        this.employers = employers;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ATTENDANCE_DATE", length=10)
    public Date getAttendanceDate() {
        return this.attendanceDate;
    }
    
    public void setAttendanceDate(Date attendanceDate) {
        this.attendanceDate = attendanceDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_TIME", length=19)
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


