package com.actop.db;
// Generated Jul 11, 2015 12:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name="departments"
    ,catalog="actop_system"
)
public class Departments  implements java.io.Serializable {


     private Integer idDepartment;
     private byte[] department;
     private Set<DepartmentsHasDesignation> departmentsHasDesignations = new HashSet<DepartmentsHasDesignation>(0);

    public Departments() {
    }

    public Departments(byte[] department, Set<DepartmentsHasDesignation> departmentsHasDesignations) {
       this.department = department;
       this.departmentsHasDesignations = departmentsHasDesignations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_DEPARTMENT", unique=true, nullable=false)
    public Integer getIdDepartment() {
        return this.idDepartment;
    }
    
    public void setIdDepartment(Integer idDepartment) {
        this.idDepartment = idDepartment;
    }

    
    @Column(name="DEPARTMENT")
    public byte[] getDepartment() {
        return this.department;
    }
    
    public void setDepartment(byte[] department) {
        this.department = department;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departments")
    public Set<DepartmentsHasDesignation> getDepartmentsHasDesignations() {
        return this.departmentsHasDesignations;
    }
    
    public void setDepartmentsHasDesignations(Set<DepartmentsHasDesignation> departmentsHasDesignations) {
        this.departmentsHasDesignations = departmentsHasDesignations;
    }




}


