package com.actop.db;
// Generated Jul 11, 2015 12:30:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DepartmentsHasDesignation generated by hbm2java
 */
@Entity
@Table(name="departments_has_designation"
    ,catalog="actop_system"
)
public class DepartmentsHasDesignation  implements java.io.Serializable {


     private int idDepartmentsHasDesignation;
     private Departments departments;
     private Designation designation;
     private Employers employers;

    public DepartmentsHasDesignation() {
    }

    public DepartmentsHasDesignation(int idDepartmentsHasDesignation, Departments departments, Designation designation, Employers employers) {
       this.idDepartmentsHasDesignation = idDepartmentsHasDesignation;
       this.departments = departments;
       this.designation = designation;
       this.employers = employers;
    }
   
     @Id 

    
    @Column(name="ID_DEPARTMENTS_has_DESIGNATION", unique=true, nullable=false)
    public int getIdDepartmentsHasDesignation() {
        return this.idDepartmentsHasDesignation;
    }
    
    public void setIdDepartmentsHasDesignation(int idDepartmentsHasDesignation) {
        this.idDepartmentsHasDesignation = idDepartmentsHasDesignation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEPARTMENTS_ID_DEPARTMENT", nullable=false)
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DESIGNATION_ID_DESIGNATION", nullable=false)
    public Designation getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(Designation designation) {
        this.designation = designation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYERS_ID_EMPLOYERS", nullable=false)
    public Employers getEmployers() {
        return this.employers;
    }
    
    public void setEmployers(Employers employers) {
        this.employers = employers;
    }




}


