package com.actop.db;
// Generated Jul 23, 2015 9:46:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmployersHasAllowances generated by hbm2java
 */
@Entity
@Table(name="employers_has_allowances"
    ,catalog="actop_system"
)
public class EmployersHasAllowances  implements java.io.Serializable {


     private Integer idEmployersHasAllowances;
     private Allowances allowances;
     private Designation designation;
     private Employers employers;
     private Set<AllowanceApproval> allowanceApprovals = new HashSet<AllowanceApproval>(0);

    public EmployersHasAllowances() {
    }

	
    public EmployersHasAllowances(Allowances allowances, Designation designation, Employers employers) {
        this.allowances = allowances;
        this.designation = designation;
        this.employers = employers;
    }
    public EmployersHasAllowances(Allowances allowances, Designation designation, Employers employers, Set<AllowanceApproval> allowanceApprovals) {
       this.allowances = allowances;
       this.designation = designation;
       this.employers = employers;
       this.allowanceApprovals = allowanceApprovals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_EMPLOYERS_has_ALLOWANCES", unique=true, nullable=false)
    public Integer getIdEmployersHasAllowances() {
        return this.idEmployersHasAllowances;
    }
    
    public void setIdEmployersHasAllowances(Integer idEmployersHasAllowances) {
        this.idEmployersHasAllowances = idEmployersHasAllowances;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ALLOWANCES_ID_ALLOWANCES", nullable=false)
    public Allowances getAllowances() {
        return this.allowances;
    }
    
    public void setAllowances(Allowances allowances) {
        this.allowances = allowances;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DESIGNATION_ID_DESIGNATION", nullable=false)
    public Designation getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(Designation designation) {
        this.designation = designation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYERS_ID_EMPLOYERS", nullable=false)
    public Employers getEmployers() {
        return this.employers;
    }
    
    public void setEmployers(Employers employers) {
        this.employers = employers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employersHasAllowances")
    public Set<AllowanceApproval> getAllowanceApprovals() {
        return this.allowanceApprovals;
    }
    
    public void setAllowanceApprovals(Set<AllowanceApproval> allowanceApprovals) {
        this.allowanceApprovals = allowanceApprovals;
    }




}


