package com.actop.db;
// Generated Jul 24, 2015 12:22:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtherApprovals generated by hbm2java
 */
@Entity
@Table(name="other_approvals"
    ,catalog="actop_system"
)
public class OtherApprovals  implements java.io.Serializable {


     private Integer otherHasDepartmentsHasDesignationId;
     private DepartmentsHasDesignation departmentsHasDesignation;
     private Other other;
     private Date approvedtime;
     private Integer status;
     private String note;

    public OtherApprovals() {
    }

	
    public OtherApprovals(DepartmentsHasDesignation departmentsHasDesignation, Other other) {
        this.departmentsHasDesignation = departmentsHasDesignation;
        this.other = other;
    }
    public OtherApprovals(DepartmentsHasDesignation departmentsHasDesignation, Other other, Date approvedtime, Integer status, String note) {
       this.departmentsHasDesignation = departmentsHasDesignation;
       this.other = other;
       this.approvedtime = approvedtime;
       this.status = status;
       this.note = note;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="OTHER_has_DEPARTMENTS_has_DESIGNATION_ID", unique=true, nullable=false)
    public Integer getOtherHasDepartmentsHasDesignationId() {
        return this.otherHasDepartmentsHasDesignationId;
    }
    
    public void setOtherHasDepartmentsHasDesignationId(Integer otherHasDepartmentsHasDesignationId) {
        this.otherHasDepartmentsHasDesignationId = otherHasDepartmentsHasDesignationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEPARTMENTS_has_DESIGNATION_ID_DEPARTMENTS_has_DESIGNATION", nullable=false)
    public DepartmentsHasDesignation getDepartmentsHasDesignation() {
        return this.departmentsHasDesignation;
    }
    
    public void setDepartmentsHasDesignation(DepartmentsHasDesignation departmentsHasDesignation) {
        this.departmentsHasDesignation = departmentsHasDesignation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OTHER_ID_OTHER", nullable=false)
    public Other getOther() {
        return this.other;
    }
    
    public void setOther(Other other) {
        this.other = other;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPROVEDTIME", length=19)
    public Date getApprovedtime() {
        return this.approvedtime;
    }
    
    public void setApprovedtime(Date approvedtime) {
        this.approvedtime = approvedtime;
    }

    
    @Column(name="STATUS")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="NOTE")
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


