package com.actop.db;
// Generated Jul 23, 2015 9:46:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Other generated by hbm2java
 */
@Entity
@Table(name="other"
    ,catalog="actop_system"
)
public class Other  implements java.io.Serializable {


     private Integer idOther;
     private Employers employers;
     private byte[] otherType;
     private byte[] location;
     private Date inDate;
     private Date outDate;
     private byte[] reson;
     private String note;
     private byte[] expenses;
     private byte[] informTo;
     private Integer claim;
     private Date claimPayed;
     private byte[] claimApprovedBy;
     private Date claimApproved;
     private Integer states;
     private Set<OtherApprovals> otherApprovalses = new HashSet<OtherApprovals>(0);

    public Other() {
    }

	
    public Other(Employers employers) {
        this.employers = employers;
    }
    public Other(Employers employers, byte[] otherType, byte[] location, Date inDate, Date outDate, byte[] reson, String note, byte[] expenses, byte[] informTo, Integer claim, Date claimPayed, byte[] claimApprovedBy, Date claimApproved, Integer states, Set<OtherApprovals> otherApprovalses) {
       this.employers = employers;
       this.otherType = otherType;
       this.location = location;
       this.inDate = inDate;
       this.outDate = outDate;
       this.reson = reson;
       this.note = note;
       this.expenses = expenses;
       this.informTo = informTo;
       this.claim = claim;
       this.claimPayed = claimPayed;
       this.claimApprovedBy = claimApprovedBy;
       this.claimApproved = claimApproved;
       this.states = states;
       this.otherApprovalses = otherApprovalses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_OTHER", unique=true, nullable=false)
    public Integer getIdOther() {
        return this.idOther;
    }
    
    public void setIdOther(Integer idOther) {
        this.idOther = idOther;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYERS_ID_EMPLOYERS", nullable=false)
    public Employers getEmployers() {
        return this.employers;
    }
    
    public void setEmployers(Employers employers) {
        this.employers = employers;
    }

    
    @Column(name="OTHER_TYPE")
    public byte[] getOtherType() {
        return this.otherType;
    }
    
    public void setOtherType(byte[] otherType) {
        this.otherType = otherType;
    }

    
    @Column(name="LOCATION")
    public byte[] getLocation() {
        return this.location;
    }
    
    public void setLocation(byte[] location) {
        this.location = location;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="IN_DATE", length=19)
    public Date getInDate() {
        return this.inDate;
    }
    
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OUT_DATE", length=19)
    public Date getOutDate() {
        return this.outDate;
    }
    
    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }

    
    @Column(name="RESON")
    public byte[] getReson() {
        return this.reson;
    }
    
    public void setReson(byte[] reson) {
        this.reson = reson;
    }

    
    @Column(name="NOTE")
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="EXPENSES")
    public byte[] getExpenses() {
        return this.expenses;
    }
    
    public void setExpenses(byte[] expenses) {
        this.expenses = expenses;
    }

    
    @Column(name="INFORM_TO")
    public byte[] getInformTo() {
        return this.informTo;
    }
    
    public void setInformTo(byte[] informTo) {
        this.informTo = informTo;
    }

    
    @Column(name="CLAIM")
    public Integer getClaim() {
        return this.claim;
    }
    
    public void setClaim(Integer claim) {
        this.claim = claim;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CLAIM_PAYED", length=19)
    public Date getClaimPayed() {
        return this.claimPayed;
    }
    
    public void setClaimPayed(Date claimPayed) {
        this.claimPayed = claimPayed;
    }

    
    @Column(name="CLAIM_APPROVED_BY")
    public byte[] getClaimApprovedBy() {
        return this.claimApprovedBy;
    }
    
    public void setClaimApprovedBy(byte[] claimApprovedBy) {
        this.claimApprovedBy = claimApprovedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CLAIM_APPROVED", length=19)
    public Date getClaimApproved() {
        return this.claimApproved;
    }
    
    public void setClaimApproved(Date claimApproved) {
        this.claimApproved = claimApproved;
    }

    
    @Column(name="STATES")
    public Integer getStates() {
        return this.states;
    }
    
    public void setStates(Integer states) {
        this.states = states;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="other")
    public Set<OtherApprovals> getOtherApprovalses() {
        return this.otherApprovalses;
    }
    
    public void setOtherApprovalses(Set<OtherApprovals> otherApprovalses) {
        this.otherApprovalses = otherApprovalses;
    }




}


