package com.actop.db;
// Generated Jul 11, 2015 12:30:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectTaskStates generated by hbm2java
 */
@Entity
@Table(name="project_task_states"
    ,catalog="actop_system"
)
public class ProjectTaskStates  implements java.io.Serializable {


     private Integer idProjectTaskStates;
     private ProjectTasks projectTasks;
     private byte[] topic;
     private Date topicStart;
     private Date topicEnd;
     private byte[] topicEstimateTime;
     private byte[] topicActualTime;
     private String topicNote;
     private byte[] topicStates;

    public ProjectTaskStates() {
    }

	
    public ProjectTaskStates(ProjectTasks projectTasks) {
        this.projectTasks = projectTasks;
    }
    public ProjectTaskStates(ProjectTasks projectTasks, byte[] topic, Date topicStart, Date topicEnd, byte[] topicEstimateTime, byte[] topicActualTime, String topicNote, byte[] topicStates) {
       this.projectTasks = projectTasks;
       this.topic = topic;
       this.topicStart = topicStart;
       this.topicEnd = topicEnd;
       this.topicEstimateTime = topicEstimateTime;
       this.topicActualTime = topicActualTime;
       this.topicNote = topicNote;
       this.topicStates = topicStates;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PROJECT_TASK_STATES", unique=true, nullable=false)
    public Integer getIdProjectTaskStates() {
        return this.idProjectTaskStates;
    }
    
    public void setIdProjectTaskStates(Integer idProjectTaskStates) {
        this.idProjectTaskStates = idProjectTaskStates;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROJECT_TASKS_ID_PROJECT_TASKS", nullable=false)
    public ProjectTasks getProjectTasks() {
        return this.projectTasks;
    }
    
    public void setProjectTasks(ProjectTasks projectTasks) {
        this.projectTasks = projectTasks;
    }

    
    @Column(name="TOPIC")
    public byte[] getTopic() {
        return this.topic;
    }
    
    public void setTopic(byte[] topic) {
        this.topic = topic;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TOPIC_START", length=19)
    public Date getTopicStart() {
        return this.topicStart;
    }
    
    public void setTopicStart(Date topicStart) {
        this.topicStart = topicStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TOPIC_END", length=19)
    public Date getTopicEnd() {
        return this.topicEnd;
    }
    
    public void setTopicEnd(Date topicEnd) {
        this.topicEnd = topicEnd;
    }

    
    @Column(name="TOPIC_ESTIMATE_TIME")
    public byte[] getTopicEstimateTime() {
        return this.topicEstimateTime;
    }
    
    public void setTopicEstimateTime(byte[] topicEstimateTime) {
        this.topicEstimateTime = topicEstimateTime;
    }

    
    @Column(name="TOPIC_ACTUAL_TIME")
    public byte[] getTopicActualTime() {
        return this.topicActualTime;
    }
    
    public void setTopicActualTime(byte[] topicActualTime) {
        this.topicActualTime = topicActualTime;
    }

    
    @Column(name="TOPIC_NOTE")
    public String getTopicNote() {
        return this.topicNote;
    }
    
    public void setTopicNote(String topicNote) {
        this.topicNote = topicNote;
    }

    
    @Column(name="TOPIC_STATES")
    public byte[] getTopicStates() {
        return this.topicStates;
    }
    
    public void setTopicStates(byte[] topicStates) {
        this.topicStates = topicStates;
    }




}


