package com.actop.db;
// Generated Jul 24, 2015 12:22:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name="projects"
    ,catalog="actop_system"
)
public class Projects  implements java.io.Serializable {


     private Integer idProjects;
     private Clients clients;
     private Employers employers;
     private byte[] projectName;
     private Date startDate;
     private Date endDate;
     private Date actualStartDate;
     private Date actualEndDate;
     private byte[] projectType;
     private byte[] projectDescription;
     private byte[] projectStatus;
     private byte[] projectManager;
     private byte[] clientNote;
     private Set<ProjectTasks> projectTaskses = new HashSet<ProjectTasks>(0);
     private Set<ProjectsApproval> projectsApprovals = new HashSet<ProjectsApproval>(0);

    public Projects() {
    }

	
    public Projects(Clients clients, Employers employers) {
        this.clients = clients;
        this.employers = employers;
    }
    public Projects(Clients clients, Employers employers, byte[] projectName, Date startDate, Date endDate, Date actualStartDate, Date actualEndDate, byte[] projectType, byte[] projectDescription, byte[] projectStatus, byte[] projectManager, byte[] clientNote, Set<ProjectTasks> projectTaskses, Set<ProjectsApproval> projectsApprovals) {
       this.clients = clients;
       this.employers = employers;
       this.projectName = projectName;
       this.startDate = startDate;
       this.endDate = endDate;
       this.actualStartDate = actualStartDate;
       this.actualEndDate = actualEndDate;
       this.projectType = projectType;
       this.projectDescription = projectDescription;
       this.projectStatus = projectStatus;
       this.projectManager = projectManager;
       this.clientNote = clientNote;
       this.projectTaskses = projectTaskses;
       this.projectsApprovals = projectsApprovals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PROJECTS", unique=true, nullable=false)
    public Integer getIdProjects() {
        return this.idProjects;
    }
    
    public void setIdProjects(Integer idProjects) {
        this.idProjects = idProjects;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENTS_ID_CLIENTS", nullable=false)
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYERS_ID_EMPLOYERS", nullable=false)
    public Employers getEmployers() {
        return this.employers;
    }
    
    public void setEmployers(Employers employers) {
        this.employers = employers;
    }

    
    @Column(name="PROJECT_NAME")
    public byte[] getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(byte[] projectName) {
        this.projectName = projectName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACTUAL_START_DATE", length=10)
    public Date getActualStartDate() {
        return this.actualStartDate;
    }
    
    public void setActualStartDate(Date actualStartDate) {
        this.actualStartDate = actualStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACTUAL_END_DATE", length=10)
    public Date getActualEndDate() {
        return this.actualEndDate;
    }
    
    public void setActualEndDate(Date actualEndDate) {
        this.actualEndDate = actualEndDate;
    }

    
    @Column(name="PROJECT_TYPE")
    public byte[] getProjectType() {
        return this.projectType;
    }
    
    public void setProjectType(byte[] projectType) {
        this.projectType = projectType;
    }

    
    @Column(name="PROJECT_DESCRIPTION")
    public byte[] getProjectDescription() {
        return this.projectDescription;
    }
    
    public void setProjectDescription(byte[] projectDescription) {
        this.projectDescription = projectDescription;
    }

    
    @Column(name="PROJECT_STATUS")
    public byte[] getProjectStatus() {
        return this.projectStatus;
    }
    
    public void setProjectStatus(byte[] projectStatus) {
        this.projectStatus = projectStatus;
    }

    
    @Column(name="PROJECT_MANAGER")
    public byte[] getProjectManager() {
        return this.projectManager;
    }
    
    public void setProjectManager(byte[] projectManager) {
        this.projectManager = projectManager;
    }

    
    @Column(name="CLIENT_NOTE")
    public byte[] getClientNote() {
        return this.clientNote;
    }
    
    public void setClientNote(byte[] clientNote) {
        this.clientNote = clientNote;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="projects")
    public Set<ProjectTasks> getProjectTaskses() {
        return this.projectTaskses;
    }
    
    public void setProjectTaskses(Set<ProjectTasks> projectTaskses) {
        this.projectTaskses = projectTaskses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="projects")
    public Set<ProjectsApproval> getProjectsApprovals() {
        return this.projectsApprovals;
    }
    
    public void setProjectsApprovals(Set<ProjectsApproval> projectsApprovals) {
        this.projectsApprovals = projectsApprovals;
    }




}


