package com.actop.db;
// Generated Jul 24, 2015 12:22:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotions generated by hbm2java
 */
@Entity
@Table(name="promotions"
    ,catalog="actop_system"
)
public class Promotions  implements java.io.Serializable {


     private Integer idPromotions;
     private Employers employers;
     private byte[] beforePromotion;
     private byte[] promotionFor;
     private Date promotionApplyDate;
     private byte[] promotBy;
     private Date promotionEffectiveDate;
     private byte[] promotionStates;
     private Set<PromotionApproval> promotionApprovals = new HashSet<PromotionApproval>(0);

    public Promotions() {
    }

	
    public Promotions(Employers employers) {
        this.employers = employers;
    }
    public Promotions(Employers employers, byte[] beforePromotion, byte[] promotionFor, Date promotionApplyDate, byte[] promotBy, Date promotionEffectiveDate, byte[] promotionStates, Set<PromotionApproval> promotionApprovals) {
       this.employers = employers;
       this.beforePromotion = beforePromotion;
       this.promotionFor = promotionFor;
       this.promotionApplyDate = promotionApplyDate;
       this.promotBy = promotBy;
       this.promotionEffectiveDate = promotionEffectiveDate;
       this.promotionStates = promotionStates;
       this.promotionApprovals = promotionApprovals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PROMOTIONS", unique=true, nullable=false)
    public Integer getIdPromotions() {
        return this.idPromotions;
    }
    
    public void setIdPromotions(Integer idPromotions) {
        this.idPromotions = idPromotions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYERS_ID_EMPLOYERS", nullable=false)
    public Employers getEmployers() {
        return this.employers;
    }
    
    public void setEmployers(Employers employers) {
        this.employers = employers;
    }

    
    @Column(name="BEFORE_PROMOTION")
    public byte[] getBeforePromotion() {
        return this.beforePromotion;
    }
    
    public void setBeforePromotion(byte[] beforePromotion) {
        this.beforePromotion = beforePromotion;
    }

    
    @Column(name="PROMOTION_FOR")
    public byte[] getPromotionFor() {
        return this.promotionFor;
    }
    
    public void setPromotionFor(byte[] promotionFor) {
        this.promotionFor = promotionFor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROMOTION_APPLY_DATE", length=10)
    public Date getPromotionApplyDate() {
        return this.promotionApplyDate;
    }
    
    public void setPromotionApplyDate(Date promotionApplyDate) {
        this.promotionApplyDate = promotionApplyDate;
    }

    
    @Column(name="PROMOT_BY")
    public byte[] getPromotBy() {
        return this.promotBy;
    }
    
    public void setPromotBy(byte[] promotBy) {
        this.promotBy = promotBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROMOTION_EFFECTIVE_DATE", length=10)
    public Date getPromotionEffectiveDate() {
        return this.promotionEffectiveDate;
    }
    
    public void setPromotionEffectiveDate(Date promotionEffectiveDate) {
        this.promotionEffectiveDate = promotionEffectiveDate;
    }

    
    @Column(name="PROMOTION_STATES")
    public byte[] getPromotionStates() {
        return this.promotionStates;
    }
    
    public void setPromotionStates(byte[] promotionStates) {
        this.promotionStates = promotionStates;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="promotions")
    public Set<PromotionApproval> getPromotionApprovals() {
        return this.promotionApprovals;
    }
    
    public void setPromotionApprovals(Set<PromotionApproval> promotionApprovals) {
        this.promotionApprovals = promotionApprovals;
    }




}


