package com.actop.db;
// Generated Jul 24, 2015 12:22:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PromotionApproval generated by hbm2java
 */
@Entity
@Table(name="promotion_approval"
    ,catalog="actop_system"
)
public class PromotionApproval  implements java.io.Serializable {


     private Integer promotionsHasDepartmentsHasDesignationId;
     private DepartmentsHasDesignation departmentsHasDesignation;
     private Promotions promotions;
     private Date datetime;
     private Integer status;
     private String note;

    public PromotionApproval() {
    }

	
    public PromotionApproval(DepartmentsHasDesignation departmentsHasDesignation, Promotions promotions) {
        this.departmentsHasDesignation = departmentsHasDesignation;
        this.promotions = promotions;
    }
    public PromotionApproval(DepartmentsHasDesignation departmentsHasDesignation, Promotions promotions, Date datetime, Integer status, String note) {
       this.departmentsHasDesignation = departmentsHasDesignation;
       this.promotions = promotions;
       this.datetime = datetime;
       this.status = status;
       this.note = note;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PROMOTIONS_has_DEPARTMENTS_has_DESIGNATION_ID", unique=true, nullable=false)
    public Integer getPromotionsHasDepartmentsHasDesignationId() {
        return this.promotionsHasDepartmentsHasDesignationId;
    }
    
    public void setPromotionsHasDepartmentsHasDesignationId(Integer promotionsHasDepartmentsHasDesignationId) {
        this.promotionsHasDepartmentsHasDesignationId = promotionsHasDepartmentsHasDesignationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEPARTMENTS_has_DESIGNATION_ID_DEPARTMENTS_has_DESIGNATION", nullable=false)
    public DepartmentsHasDesignation getDepartmentsHasDesignation() {
        return this.departmentsHasDesignation;
    }
    
    public void setDepartmentsHasDesignation(DepartmentsHasDesignation departmentsHasDesignation) {
        this.departmentsHasDesignation = departmentsHasDesignation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROMOTIONS_ID_PROMOTIONS", nullable=false)
    public Promotions getPromotions() {
        return this.promotions;
    }
    
    public void setPromotions(Promotions promotions) {
        this.promotions = promotions;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATETIME", length=19)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    
    @Column(name="STATUS")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="NOTE")
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


