package com.actop.db;
// Generated Jul 23, 2015 9:46:44 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.ColumnTransformer;

/**
 * SpecialHolidays generated by hbm2java
 */
@Entity
@Table(name = "special_holidays", catalog = "actop_system"
)
public class SpecialHolidays implements java.io.Serializable {

    private Integer idSpecialHolidays;
    private byte[] holidayType;
    private Date startDate;
    private Date endDate;

    public SpecialHolidays() {
    }

    public SpecialHolidays(byte[] holidayType, Date startDate, Date endDate) {
        this.holidayType = holidayType;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idSPECIAL_HOLIDAYS", unique = true, nullable = false)
    public Integer getIdSpecialHolidays() {
        return this.idSpecialHolidays;
    }

    public void setIdSpecialHolidays(Integer idSpecialHolidays) {
        this.idSpecialHolidays = idSpecialHolidays;
    }

    @Column(name = "HOLIDAY_TYPE")
    @ColumnTransformer(
            read = "AES_DECRYPT(encryptedBody, 'Actop@123456')",
            write = "AES_ENCRYPT(?, 'Actop@123456')")
    public byte[] getHolidayType() {
        return this.holidayType;
    }

    public void setHolidayType(byte[] holidayType) {
        this.holidayType = holidayType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "START_DATE", length = 10)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "END_DATE", length = 10)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

}
