package com.actop.db;
// Generated Jul 23, 2015 9:46:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserLogin generated by hbm2java
 */
@Entity
@Table(name="user_login"
    ,catalog="actop_system"
)
public class UserLogin  implements java.io.Serializable {


     private Integer idUserLogin;
     private Employers employers;
     private byte[] un;
     private byte[] pw;
     private byte[] securityq1;
     private byte[] answer1;
     private byte[] securityq2;
     private byte[] answer2;
     private Set<InterfacesHasUserLogin> interfacesHasUserLogins = new HashSet<InterfacesHasUserLogin>(0);

    public UserLogin() {
    }

	
    public UserLogin(Employers employers) {
        this.employers = employers;
    }
    public UserLogin(Employers employers, byte[] un, byte[] pw, byte[] securityq1, byte[] answer1, byte[] securityq2, byte[] answer2, Set<InterfacesHasUserLogin> interfacesHasUserLogins) {
       this.employers = employers;
       this.un = un;
       this.pw = pw;
       this.securityq1 = securityq1;
       this.answer1 = answer1;
       this.securityq2 = securityq2;
       this.answer2 = answer2;
       this.interfacesHasUserLogins = interfacesHasUserLogins;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_User_Login", unique=true, nullable=false)
    public Integer getIdUserLogin() {
        return this.idUserLogin;
    }
    
    public void setIdUserLogin(Integer idUserLogin) {
        this.idUserLogin = idUserLogin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYERS_ID_EMPLOYERS", nullable=false)
    public Employers getEmployers() {
        return this.employers;
    }
    
    public void setEmployers(Employers employers) {
        this.employers = employers;
    }

    
    @Column(name="un")
    public byte[] getUn() {
        return this.un;
    }
    
    public void setUn(byte[] un) {
        this.un = un;
    }

    
    @Column(name="pw")
    public byte[] getPw() {
        return this.pw;
    }
    
    public void setPw(byte[] pw) {
        this.pw = pw;
    }

    
    @Column(name="securityq1")
    public byte[] getSecurityq1() {
        return this.securityq1;
    }
    
    public void setSecurityq1(byte[] securityq1) {
        this.securityq1 = securityq1;
    }

    
    @Column(name="answer1")
    public byte[] getAnswer1() {
        return this.answer1;
    }
    
    public void setAnswer1(byte[] answer1) {
        this.answer1 = answer1;
    }

    
    @Column(name="securityq2")
    public byte[] getSecurityq2() {
        return this.securityq2;
    }
    
    public void setSecurityq2(byte[] securityq2) {
        this.securityq2 = securityq2;
    }

    
    @Column(name="answer2")
    public byte[] getAnswer2() {
        return this.answer2;
    }
    
    public void setAnswer2(byte[] answer2) {
        this.answer2 = answer2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userLogin")
    public Set<InterfacesHasUserLogin> getInterfacesHasUserLogins() {
        return this.interfacesHasUserLogins;
    }
    
    public void setInterfacesHasUserLogins(Set<InterfacesHasUserLogin> interfacesHasUserLogins) {
        this.interfacesHasUserLogins = interfacesHasUserLogins;
    }




}


